#AcquirerReferenceNumber.cpp \
#ActionCode.cpp \
#AmountReconciliation.cpp \
#AmountsFees.cpp \
#AmountsOriginal.cpp \
#AmountsOriginalFees.cpp \
#ApprovalCode.cpp \
#AuthorizationLifeCycleCode.cpp \
#AuthorizingAgentInstitutionIdentificationCode.cpp \
#BinaryTLV.cpp \
#BinaryTLVs.cpp \
#ConversionRateReconciliation.cpp \
#DataRecord.cpp \
#DateAction.cpp \
#DateAndTimeLocalTransaction.cpp \
#DateEffective.cpp \
#DateReconciliation.cpp \
#ElectronicCommerceData.cpp \
#ExtendedPaymentData.cpp \
#FileTransferControlData.cpp \
#FileTransferDescriptionData.cpp \
#FileTransferMessageControl.cpp \
#FunctionCode.cpp \
#ICCSystemRelatedData.cpp \
#KeyManagementData.cpp \
#MerchantCategoryCode.cpp \
#MessageErroIndicator.cpp \
#MessageReasonCode.cpp \
#NetReconciliationAmount.cpp \
#POSCapability.cpp \
#POSDataCode.cpp \
#ReconciliationDataPrimary.cpp \
#ReconciliationDataSecondary.cpp \
#ReconciliationFeeAmountsCredit.cpp \
#ReconciliationFeeAmountsDebit.cpp \
#ReconciliationIndicator.cpp \
#ServiceCode.cpp \
#TransactionDestinationInstitutionIdentificationCode.cpp \
#TransactionLifeCycleIdentificationData.cpp \
#TransactionOriginatorInstitutionIdentificationCode.cpp \
#TransactionSpecificData.cpp \
#VerificationData.cpp 

CPP_SRCS += \
AccountIdentification1.cpp \
AccountIdentification2.cpp \
AcquiringInstitutionCountryCode.cpp \
AcquiringInstitutionIdentificationCode.cpp \
AdditionalAmounts.cpp \
AdditionalDataISO.cpp \
AdditionalDataNational.cpp \
AdditionalDataPrivate.cpp \
AdditionalResponseData.cpp \
AuthorizationIdentificationResponse.cpp \
AuthorizationIdentificationResponseLength.cpp \
Bitmap.cpp \
CardAcceptorIdentificationCode.cpp \
CardAcceptorNameOrlocation.cpp \
CardAcceptorTerminalIdentification.cpp \
CardHolderBillingAmount.cpp \
CardHolderBillingConversionRate.cpp \
CardHolderBillingCurrencyCode.cpp \
CardIssuerReferenceData.cpp \
CardSequenceNumber.cpp \
CardHolderBillingFeeAmount.cpp \
Constructed.cpp \
DataElement.cpp \
CaptureDate.cpp \
ConversionDate.cpp \
ExpirationDate.cpp \
SettlementDate.cpp \
Exception.cpp \
Field.cpp \
FileName.cpp \
ForwardingInstitutionCountryCode.cpp \
ForwardingInstitutionIdentificationCode.cpp \
MACField.cpp \
MerchantType.cpp \
NationalData.cpp \
NetworkInternationalIdentifier.cpp \
OriginalDataElements.cpp \
PINData.cpp \
Payee.cpp \
PointOfServiceConditionCode.cpp \
PointOfServiceEntryMode.cpp \
PointOfServicePINCaptureCode.cpp \
PrimaryAccountNumber.cpp \
PrimaryAccountNumberCountryCode.cpp \
PrimaryAccountNumberExtended.cpp \
ProcessingCode.cpp \
ReceivingInstitutionIdentificationCode.cpp \
ResponseCode.cpp \
RetrievalReferenceNumber.cpp \
SecurityRelatedControlInformation.cpp \
ServiceRestrictionCode.cpp \
SettlementAmount.cpp \
SettlementConversionRate.cpp \
SettlementCurrencyCode.cpp \
SettlementFeeAmount.cpp \
SettlementInstitutionIdentificationCode.cpp \
SettlementProcessingFeeAmount.cpp \
SystemsTraceAuditNumber.cpp \
TLV.cpp \
Tag.cpp \
Track1Data.cpp \
Track2Data.cpp \
Track3Data.cpp \
TransactionAmount.cpp \
TransactionCurrencyCode.cpp \
TransactionFeeAmount.cpp \
TransactionLocalDate.cpp \
TransactionLocalTime.cpp \
TransactionProcessingFeeAmount.cpp \
TransactionProcessingFeeAmout.cpp \
TransmissionDateAndTime.cpp
