include source.mk

include $(BASE)/build/rules/global

objects = $(patsubst %.cpp,%,$(CPP_SRCS))

target         = ISO-8583-DTT
target_version = $(LIBVERSION)
target_libs    =

include $(BASE)/build/rules/lib
