CPP_SRCS += \
AlphaNumeric.cpp \
AlphaNumericBinary.cpp \
AlphaNumericSpace.cpp \
AlphaNumericSpecial.cpp \
Alphabetic.cpp \
BinaryInputOutputStream.cpp \
BinaryInputStream.cpp \
BinaryOutputStream.cpp \
Bitmaps.cpp \
Buffer.cpp \
Bytes.cpp \
Century.cpp \
Day.cpp \
Exception.cpp \
Hour.cpp \
ISO-8583-DTT.cpp \
LL.cpp \
LLAlphaNumeric.cpp \
LLAlphaNumericSpace.cpp \
LLAlphaNumericSpecial.cpp \
LLAlphabetic.cpp \
LLBytes.cpp \
LLL.cpp \
LLLAlphaNumeric.cpp \
LLLAlphaNumericSpecial.cpp \
LLLBytes.cpp \
LLLL.cpp \
LLLLAlphaNumericSpecial.cpp \
LLLLBytes.cpp \
LLNumeric.cpp \
LLNumericSpecial.cpp \
Millisecond.cpp \
Minute.cpp \
Month.cpp \
Numeric.cpp \
NumericSpecial.cpp \
Range.cpp \
Second.cpp \
SignedNumeric.cpp \
Year.cpp \
Zoned.cpp 
