CPP_SRCS += \
AdministrativeAdvice.cpp \
AdministrativeAdviceResponse.cpp \
AdministrativeInstruction.cpp \
AdministrativeInstructionAcknowledge.cpp \
AdministrativeNotification.cpp \
AdministrativeNotificationAcknowledge.cpp \
AdministrativeRequest.cpp \
AdministrativeRequestResponse.cpp \
AuthorizationAdvice.cpp \
AuthorizationAdviceResponse.cpp \
AuthorizationInstruction.cpp \
AuthorizationInstructionAcknowledge.cpp \
AuthorizationNotification.cpp \
AuthorizationNotificationAcknowledge.cpp \
AuthorizationRequest.cpp \
AuthorizationRequestResponse.cpp \
Exception.cpp \
Factory.cpp \
FileActionAdvice.cpp \
FileActionAdviceResponse.cpp \
FileActionInstruction.cpp \
FileActionInstructionAcknowledge.cpp \
FileActionNotification.cpp \
FileActionNotificationAcknowledge.cpp \
FileActionRequest.cpp \
FileActionRequestResponse.cpp \
FinancialAdvice.cpp \
FinancialAdviceResponse.cpp \
FinancialInstruction.cpp \
FinancialInstructionAcknowledge.cpp \
FinancialNotification.cpp \
FinancialNotificationAcknowledge.cpp \
FinancialRequest.cpp \
FinancialRequestResponse.cpp \
ISO-8583-MSG.cpp \
MTI.cpp \
Message.cpp \
NetworkAdvice.cpp \
NetworkAdviceResponse.cpp \
NetworkChannel.cpp \
NetworkInstruction.cpp \
NetworkInstructionAcknowledge.cpp \
NetworkNotification.cpp \
NetworkNotificationAcknowledge.cpp \
NetworkRequest.cpp \
NetworkRequestResponse.cpp \
ReconciliationAdvice.cpp \
ReconciliationAdviceResponse.cpp \
ReconciliationInstruction.cpp \
ReconciliationInstructionAcknowledge.cpp \
ReconciliationNotification.cpp \
ReconciliationNotificationAcknowledge.cpp \
ReconciliationRequest.cpp \
ReconciliationRequestResponse.cpp \
Request.cpp \
RequestResponse.cpp \
ReversalAdvice.cpp \
ReversalAdviceResponse.cpp \
ReversalInstruction.cpp \
ReversalInstructionAcknowledge.cpp \
ReversalNotification.cpp \
ReversalNotificationAcknowledge.cpp \
ReversalRequest.cpp \
ReversalRequestResponse.cpp \
SocketChannel.cpp \
TestEchoRequest.cpp \
TestEchoRequestResponse.cpp 
